export enum SELECT_DOCTOR_FORM_FIELDS {
    NAME = "NAME",
    BIRTHDAY_DATE = "BIRTHDAY_DATE",
    SEX = "SEX",
    CITY = "CITY",
    DOCTOR = "DOCTOR",
    DOCTOR_SPECIALITY = "DOCTOR_SPECIALITY",
    EMAIL = "EMAIL",
    PHONE_NUMBER = "PHONE_NUMBER",
}